### ISSUE TITLE
这个项目真的是开源嘛。。。

### ISSUE THREAD

**Issue by LawrenceHan** [lcepy/manong-reading#10]
`git clone`后，`pod install`了，就是各种编译不了
能不能出一个编译指南。。。
## 模拟器报错如下:

<img width="832" alt="screen shot 2015-07-30 at 11 48 32" src="https://cloud.githubusercontent.com/assets/7960810/8975437/f3f77440-36b0-11e5-896b-1efe50fa4e1c.png">

**Comment by icepy** [comment]
看起来..好像是微信的静态库没编译通过，你在tag里查看一下，App Group 是跟那个扩展有关系的，不应该呀。

**Comment by icepy** [comment]
你在link里把那个x86的静态包删除，那个是我用来跑模拟器做测试用的，因为微信要跑在真机，我嫌弃它麻烦....这个包我没传，或者你在微信网站上下载一份SDK，把这个x86版本的静态库导入，也可以解决这个问题。
