### ISSUE TITLE
Please specified pod version for all the pods

### ISSUE THREAD

**Issue by xingheng** [lcepy/manong-reading#8]
Some SDK APIs have changed in latest version of SCLAlertView-Objective-C (0.6.1), please check it.

**Comment by icepy** [comment]
Ok, have a time I will check it , but I used version (0.7.2),then you ?

**Comment by xingheng** [comment]
Installing Masonry (0.6.1)
Installing PNChart (0.8.2)
Installing SCLAlertView-Objective-C (0.6.1)
Installing UICountingLabel (1.0.0)

-- 
Will Han
Sent with Airmail

On June 26, 2015 at 5:19:12 PM, lcepy (notifications@github.com) wrote:

Ok, have a time I will check it , but I used version (0.7.1) ，then you ?

**Comment by icepy** [comment]
because my podfile not specified version , so ... to compile this project  you specified version for your podfile,tonight i will check it.

**Comment by icepy** [comment]
0.7.2+ SCLAlertView-Objective-C
